import {ClerkProvider} from "@clerk/nextjs";
import {Quicksand} from "next/font/google";
import AntdRegistery from "../utils/AntdRegistery";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ThemeProvider from "@/utils/ThemeProvider";
import "./globals.css";
import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const body = Quicksand({subsets: ["latin"]});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={body.className}>
          <AntdRegistery>
            <AntdRegistry>
              <ThemeProvider>
                <Header />
                {children}
                <Footer />
              </ThemeProvider>
            </AntdRegistry>
          </AntdRegistery>
        </body>
      </ClerkProvider>
    </html>
  );
}
